"use strict";
(function () {
  const ES=window.EDITOR_STORY, DUN=window.EDITOR_DUNGEONS||[];
  const emptyStory=ES.emptyStory, storyFromSaved=ES.storyFromSaved, storyToSaved=ES.storyToSaved;
  const histButtonHTML=ES.histButtonHTML, openHistoryEditor=ES.openHistoryEditor, previewStory=ES.previewStory;
  const C={id:"nova_campanha",name:"Nova Campanha",intro:emptyStory(),outro:emptyStory(),scene_intro:"",scene_triggers:[]};
  const esc=v=>String(v==null?"":v).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
  const csv=v=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean);
  let sceneLibraryRequested=false;
  const sceneList=()=>Object.entries((window.EDITOR_SCENES&&window.EDITOR_SCENES.getData&&window.EDITOR_SCENES.getData().scenes)||{}).map(([id,s])=>({id,name:(s&&s.name)||id}));
  const sceneIds=()=>sceneList().map(s=>s.id);
  function statusEl(){return document.getElementById("status");}
  function validarCampanhaEditor(){const erros=[];if(!C.id.trim())erros.push("id vazio");if(!C.name.trim())erros.push("nome vazio");(C.scene_triggers||[]).forEach((t,i)=>{if(!t.scene_id)erros.push("gatilho "+(i+1)+" sem cena");if(t.when==="dungeon_enter"&&!t.dungeon_file)erros.push("gatilho "+(i+1)+" sem masmorra");if(["keyword_obtained","key_item_obtained"].includes(t.when)&&!t.trigger_value)erros.push("gatilho "+(i+1)+" sem palavra-chave/item");});return {ok:!erros.length,erros};}
  function updateCampaignStatus(){const v=validarCampanhaEditor(),el=statusEl();if(!el)return v;el.className=v.ok?"status-ok":"status-err";el.textContent=v.ok?"✓ campanha válida — "+C.scene_triggers.length+" gatilho(s) de cena":"✕ "+v.erros.join("; ");return v;}
  function renderTriggers(host){
    const scenes=sceneList(),ids=scenes.map(s=>s.id),dungeons=DUN.map(d=>'<option value="'+esc(d.file)+'">'+esc(d.name||d.file)+'</option>').join('');
    host.innerHTML='<section id="campaign-scene-triggers"><h3>Cenas e gatilhos</h3><p>Várias cenas podem usar o mesmo evento; requisitos definem qual será iniciada.</p><datalist id="campaign-scene-ids">'+scenes.map(s=>'<option value="'+esc(s.id)+'" label="'+esc(s.name)+'">').join('')+'</datalist><datalist id="campaign-dungeon-files">'+dungeons+'</datalist></section>';
    if(!sceneLibraryRequested&&window.EDITOR_SCENES&&window.EDITOR_SCENES.load&&!scenes.length){sceneLibraryRequested=true;window.EDITOR_SCENES.load().then(()=>renderCampaign());}
    const box=host.querySelector('#campaign-scene-triggers');
    (C.scene_triggers||[]).forEach((t,i)=>{
      const req=t.requires||{},row=document.createElement('div');row.className='campaign-scene-trigger';
      row.innerHTML='<b>Gatilho '+(i+1)+'</b><label>Cena<input data-k="scene_id" list="campaign-scene-ids" value="'+esc(t.scene_id)+'"></label><label>Quando<select data-k="when"><option value="campaign_start">Início da campanha</option><option value="city_enter">Entrar na cidade</option><option value="dungeon_enter">Entrar na masmorra</option><option value="dungeon_complete">Concluir masmorra</option><option value="keyword_obtained">Obter palavra-chave</option><option value="key_item_obtained">Obter item-chave</option></select></label><label>Palavra-chave / item que aciona<input data-k="trigger_value" value="'+esc(t.trigger_value||'')+'" placeholder="id exato"></label><label>Local / masmorra<input data-k="dungeon_file" list="campaign-dungeon-files" value="'+esc(t.dungeon_file||'')+'" placeholder="necessário ao entrar"></label><label>Palavras: todas<input data-r="keywords_all" value="'+esc((req.keywords_all||[]).join(', '))+'"></label><label>Palavras: qualquer<input data-r="keywords_any" value="'+esc((req.keywords_any||[]).join(', '))+'"></label><label>Palavras: não possuir<input data-r="keywords_not" value="'+esc((req.keywords_not||[]).join(', '))+'"></label><label>Itens-chave: todos<input data-r="key_items_all" value="'+esc((req.key_items_all||[]).join(', '))+'"></label><label>Itens-chave: qualquer<input data-r="key_items_any" value="'+esc((req.key_items_any||[]).join(', '))+'"></label><label>Itens-chave: não possuir<input data-r="key_items_not" value="'+esc((req.key_items_not||[]).join(', '))+'"></label><label><input data-k="once" type="checkbox" '+(t.once!==false?'checked':'')+'> apenas uma vez</label><button data-del>Excluir</button>';
      box.appendChild(row);row.querySelector('[data-k="when"]').value=t.when||'campaign_start';
      row.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{t[el.dataset.k]=el.type==='checkbox'?el.checked:el.value.trim();updateCampaignStatus();});
      row.querySelectorAll('[data-r]').forEach(el=>el.onchange=()=>{t.requires=t.requires||{};t.requires[el.dataset.r]=csv(el.value);});
      row.querySelector('[data-del]').onclick=()=>{C.scene_triggers.splice(i,1);renderCampaign();};
    });
    const add=document.createElement('button');add.textContent='+ Adicionar gatilho de cena';add.onclick=()=>{C.scene_triggers.push({scene_id:ids[0]||'',when:'campaign_start',trigger_value:'',dungeon_file:'',once:true,requires:{}});renderCampaign();};box.appendChild(add);
  }
  function renderControls(){const host=document.getElementById('campaign-controls');host.innerHTML='<label>id <input id="c-id" size="12"></label><label>nome <input id="c-name" size="14"></label><label title="Escolha uma cena da Biblioteca de Cenas para executar após montar o grupo">cena inicial <input id="c-scene-intro" list="campaign-scene-ids" size="16" placeholder="opcional"></label>'+histButtonHTML('c-intro-hist',C.intro).replace('história','abertura')+histButtonHTML('c-outro-hist',C.outro).replace('história','final')+'<button id="c-load">Carregar</button><input id="c-file" type="file" accept=".json,application/json" hidden><button id="c-save">Salvar</button><div id="campaign-trigger-host"></div>';host.querySelector('#c-id').value=C.id;host.querySelector('#c-name').value=C.name;host.querySelector('#c-scene-intro').value=C.scene_intro||'';host.querySelector('#c-id').oninput=e=>{C.id=e.target.value;updateCampaignStatus();};host.querySelector('#c-name').oninput=e=>{C.name=e.target.value;updateCampaignStatus();};host.querySelector('#c-scene-intro').oninput=e=>C.scene_intro=e.target.value.trim();host.querySelector('.c-intro-hist').onclick=()=>openHistoryEditor(C.intro,'abertura da campanha',renderCampaign);host.querySelector('.c-outro-hist').onclick=()=>openHistoryEditor(C.outro,'final da campanha',renderCampaign);host.querySelector('#c-save').onclick=saveCampaign;host.querySelector('#c-load').onclick=()=>host.querySelector('#c-file').click();host.querySelector('#c-file').onchange=ev=>{const f=ev.target.files[0];if(!f)return;const fr=new FileReader();fr.onload=()=>{try{loadCampaign(JSON.parse(fr.result));}catch(e){alert('JSON inválido: '+e.message);}};fr.readAsText(f);ev.target.value='';};renderTriggers(host.querySelector('#campaign-trigger-host'));}
  function renderCampaign(){renderControls();updateCampaignStatus();}
  function setMsg(cls,msg){const el=statusEl();if(el){el.className=cls;el.textContent=msg;}}
  function baixar(out){const b=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(C.id.trim()||'campanha')+'.json';document.body.appendChild(a);a.click();a.remove();}
  function saveCampaign(){const v=updateCampaignStatus();if(!v.ok){alert('Campanha inválida:\n- '+v.erros.join('\n- '));return;}const out={schema_version:1,id:C.id.trim(),name:C.name.trim()};const intro=storyToSaved(C.intro),outro=storyToSaved(C.outro);if(intro!==undefined)out.intro=intro;if(outro!==undefined)out.outro=outro;if(C.scene_intro)out.scene_intro=C.scene_intro;if(C.scene_triggers.length)out.scene_triggers=C.scene_triggers.map(t=>({scene_id:t.scene_id,when:t.when,trigger_value:t.trigger_value||undefined,dungeon_file:t.dungeon_file||undefined,once:t.once!==false,requires:t.requires||{}}));if(!window.EDITOR_SAVE||!window.EDITOR_SAVE.saveCampaign){baixar(out);return;}setMsg('status-ok','Salvando em campaigns/…');window.EDITOR_SAVE.saveCampaign(out).then(r=>setMsg('status-ok','✓ salva em campaigns/'+r.file)).catch(e=>{baixar(out);setMsg('status-err','⚠ servidor offline ('+e.message+') — baixada em Downloads');});}
  function loadCampaign(obj){C.id=obj.id||'campanha';C.name=obj.name||'Campanha';C.intro=storyFromSaved(obj.intro);C.outro=storyFromSaved(obj.outro);C.scene_intro=obj.scene_intro||'';C.scene_triggers=Array.isArray(obj.scene_triggers)?obj.scene_triggers:[];renderCampaign();}
  window.EDITOR_CAMPAIGN={C,renderCampaign,validarCampanhaEditor,saveCampaign,loadCampaign,previewStory};
})();
