"""Guia das lições do Bardo no Campo de Treinamento (pt + en)."""
from tutorial_guia_comum import P

GUIA = {
    "fala_13": [
        P("atacar", ("Acerte o boneco: é o primeiro compasso da balada.", "Hit the dummy: the first beat of the ballad."),
          porque=("O [[d20]] mais seu acerto precisa igualar ou passar a [[ca]].",
                  "The [[d20]] plus your attack bonus must match or beat the [[ca]]."),
          ui="monstro:boneco_treino"),
    ],
    "fala_14": [
        P("matar", ("Derrube o boneco.", "Take down the dummy."),
          porque=("Sua arma é a Canção Heroica: aliados num raio de cinco casas lutam melhor, e ela cobra [[manutencao]].",
                  "Your weapon is the Heroic Song: allies within five squares fight better, and it costs [[manutencao]]."),
          ui="monstro:boneco_treino"),
    ],
    "treino_harpa": [
        P("bau", ("Fique ao lado do baú, clique nele e pegue a Harpa Velha.",
                  "Stand next to the chest, click it and take the Old Harp."),
          porque=("Cada instrumento dá uma habilidade; a harpa lança uma lâmina de som.",
                  "Each instrument grants an ability; the harp throws a blade of sound."),
          ui="casa:[10,22]",
          dica=[("Com o baú aberto, clique em Pegar ao lado da harpa.",
                 "With the chest open, click Take next to the harp.")],
          conclui={"tipo": "pegar_item", "alvo": "instrumento_harpa_velho"}),
        P("equipar", ("Abra a bolsa com [[atalho:inventario]] e dê dois cliques na Harpa Velha.",
                      "Open your bag with [[atalho:inventario]] and double-click the Old Harp."),
          porque=("Equipar é [[acao_livre]]; a harpa ocupa a mão do escudo e o Alaúde volta à bolsa.",
                  "Equipping is a [[acao_livre]]; the harp takes the shield hand and the Lute returns to the bag."),
          ui="bolsa:instrumento_harpa_velho"),
    ],
    "treino_nota_cortante": [
        P("linha", ("Ande até a casa marcada, na mesma linha do boneco, e clique em Entendi.",
                    "Walk to the marked square, in the dummy's row, then click Got it."),
          porque=("A lâmina de som segue em linha reta, até 3 casas, e não faz curva.",
                  "The blade of sound flies straight, up to 3 squares, and cannot turn."),
          ui="casa:[10,24]"),
        P("tocar", ("Clique em Nota Cortante e depois na casa vizinha que aponta para o boneco.",
                    "Click Cutting Note, then the adjacent square that points at the dummy."),
          porque=("O alvo faz um [[teste_resistencia]] de Reflexos: resistir corta o dano pela metade.",
                  "The target makes a Reflex [[teste_resistencia]]: resisting halves the damage."),
          ui="botao:instrumento",
          dica=[("Instrumento de duas mãos exige a ação principal livre neste turno.",
                 "A two-handed instrument needs your main action free this turn.")]),
    ],
    "treino_alaude": [
        P("alaude", ("Abra a bolsa com [[atalho:inventario]] e equipe o Alaúde Velho de volta.",
                     "Open your bag with [[atalho:inventario]] and equip the Old Lute again."),
          porque=("O Alaúde é passivo: não tem botão, mas reforça a Canção Heroica.",
                  "The Lute is passive: it has no button, but it reinforces the Heroic Song."),
          ui="bolsa:instrumento"),
    ],
    "treino_cancao": [
        P("cancao", ("Clique em Canção Heroica e marque Acerto.", "Click Heroic Song and tick Attack."),
          porque=("A [[sinfonia]] do Alaúde Velho soma +1 ao acerto: a canção sobe de +1 para +2.",
                  "The Old Lute's [[sinfonia]] adds +1 to attack: the song goes from +1 to +2."),
          ui="habilidade:cancao_heroica",
          dica=[("Sem Acerto marcado, a Sinfonia não reforça nada: desative a canção e tente de novo.",
                 "Without Attack ticked the Symphony reinforces nothing: turn the song off and retry.")]),
    ],
    "treino_cancao_manter": [
        P("manter", ("Clique em Encerrar Turno com a canção ativa.", "Click End Turn with the song active."),
          porque=("Ela cobra [[manutencao]] de comida e água a cada rodada.",
                  "It charges [[manutencao]] in food and water every round."),
          ui="botao:encerrar_turno"),
    ],
    "treino_cancao_parar": [
        P("parar", ("Desative a Canção Heroica.", "Turn off the Heroic Song."),
          porque=("Assim o efeito e o gasto de recursos acabam.", "That ends the effect and the resource drain.")),
    ],
    "treino_provocar": [
        P("provocar", ("Clique em Provocação e depois no boneco.", "Click Taunt and then the dummy."),
          porque=("O alvo faz um [[teste_resistencia]]; resistir não invalida o uso.",
                  "The target makes a [[teste_resistencia]]; resisting does not invalidate the use."),
          ui="habilidade:provocacao"),
    ],
    "porta_bard": [
        P("porta", ("Abra a porta marcada e entre: é a sala exclusiva do seu herói.",
                    "Open the marked door and walk in: it is your hero's exclusive room."),
          porque=("Só a sua classe entra ali; lá você treina cada habilidade do seu herói.",
                  "Only your class can enter; there you practice each of your hero's abilities."),
          ui="porta:[15,23]",
          dica=[("Clique na porta para abri-la e depois ande até ela.",
                 "Click the door to open it, then walk onto it.")]),
    ],
    "volta_bard": [
        P("sair", ("Saia da sala pela porta marcada e volte ao corredor.",
                   "Leave the room through the marked door and return to the corridor."),
          porque=("O treino da sua classe acabou; as outras lições continuam nas salas seguintes.",
                  "Your class training is over; the other lessons continue in the next rooms."),
          ui="porta:[15, 23]".replace(" ", ""),
          conclui={"tipo": "mover_ate", "alvo": [15, 23]}),
        P("seguir", ("Siga para a próxima sala e ande até a casa marcada.",
                     "Head to the next room and walk to the marked square."),
          porque=("Lá o Mestre de Armas ensina comida, água, itens e o resto do arsenal.",
                  "There the Weapon Master teaches food, water, items and the rest of the arsenal."),
          ui="casa:[28,15]",
          dica=[("Abrir porta é grátis: clique nela e siga em frente.",
                 "Opening a door is free: click it and keep going.")]),
    ],
}
